-- Table des fiches de révision publiques
create table if not exists public.fiches_revision (
    id bigint generated by default as identity primary key,
    titre text not null,
    matiere text not null,
    questions jsonb not null default '[]'::jsonb,
    auteur_id uuid not null references auth.users(id) on delete cascade,
    auteur_identifiant text not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz
);

alter table public.fiches_revision enable row level security;

drop policy if exists "Tout le monde peut lire les fiches de révision" on public.fiches_revision;
create policy "Tout le monde peut lire les fiches de révision"
on public.fiches_revision
for select
to anon, authenticated
using (true);

drop policy if exists "Les utilisateurs connectés peuvent publier des fiches de révision" on public.fiches_revision;
create policy "Les utilisateurs connectés peuvent publier des fiches de révision"
on public.fiches_revision
for insert
to authenticated
with check (auth.uid() = auteur_id);

drop policy if exists "Les auteurs peuvent modifier leurs fiches de révision" on public.fiches_revision;
create policy "Les auteurs peuvent modifier leurs fiches de révision"
on public.fiches_revision
for update
to authenticated
using (auth.uid() = auteur_id)
with check (auth.uid() = auteur_id);

drop policy if exists "Les auteurs peuvent supprimer leurs fiches de révision" on public.fiches_revision;
create policy "Les auteurs peuvent supprimer leurs fiches de révision"
on public.fiches_revision
for delete
to authenticated
using (auth.uid() = auteur_id);

drop policy if exists "Admin peut tout gérer sur les fiches de révision" on public.fiches_revision;
create policy "Admin peut tout gérer sur les fiches de révision"
on public.fiches_revision
for all
to authenticated
using (auth.uid() = 'ee633883-9e1b-45b4-8e21-94ba26ab1897'::uuid)
with check (auth.uid() = 'ee633883-9e1b-45b4-8e21-94ba26ab1897'::uuid);
